//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPanelDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FP_ControlPanelEntities : DbContext
    {
        public FP_ControlPanelEntities()
            : base("name=FP_ControlPanelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Tbl_LookupTable> Tbl_LookupTable { get; set; }
    
        public virtual ObjectResult<sp_getLookups_Result> sp_getLookups(Nullable<int> fld_Field_PerantID, Nullable<int> fld_Field_DepandancyID)
        {
            var fld_Field_PerantIDParameter = fld_Field_PerantID.HasValue ?
                new ObjectParameter("fld_Field_PerantID", fld_Field_PerantID) :
                new ObjectParameter("fld_Field_PerantID", typeof(int));
    
            var fld_Field_DepandancyIDParameter = fld_Field_DepandancyID.HasValue ?
                new ObjectParameter("fld_Field_DepandancyID", fld_Field_DepandancyID) :
                new ObjectParameter("fld_Field_DepandancyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getLookups_Result>("sp_getLookups", fld_Field_PerantIDParameter, fld_Field_DepandancyIDParameter);
        }
    
        public virtual int sp_InsertLookups(string fld_Field_Text, Nullable<int> fld_Field_PerantID, Nullable<int> fld_Field_DepandancyID)
        {
            var fld_Field_TextParameter = fld_Field_Text != null ?
                new ObjectParameter("fld_Field_Text", fld_Field_Text) :
                new ObjectParameter("fld_Field_Text", typeof(string));
    
            var fld_Field_PerantIDParameter = fld_Field_PerantID.HasValue ?
                new ObjectParameter("fld_Field_PerantID", fld_Field_PerantID) :
                new ObjectParameter("fld_Field_PerantID", typeof(int));
    
            var fld_Field_DepandancyIDParameter = fld_Field_DepandancyID.HasValue ?
                new ObjectParameter("fld_Field_DepandancyID", fld_Field_DepandancyID) :
                new ObjectParameter("fld_Field_DepandancyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertLookups", fld_Field_TextParameter, fld_Field_PerantIDParameter, fld_Field_DepandancyIDParameter);
        }
    
        public virtual int sp_LookupDisactive(Nullable<int> fld_Field_ID)
        {
            var fld_Field_IDParameter = fld_Field_ID.HasValue ?
                new ObjectParameter("fld_Field_ID", fld_Field_ID) :
                new ObjectParameter("fld_Field_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LookupDisactive", fld_Field_IDParameter);
        }
    
        public virtual int sp_LookupUpdate(Nullable<int> fld_Field_ID, string fld_Field_Text)
        {
            var fld_Field_IDParameter = fld_Field_ID.HasValue ?
                new ObjectParameter("fld_Field_ID", fld_Field_ID) :
                new ObjectParameter("fld_Field_ID", typeof(int));
    
            var fld_Field_TextParameter = fld_Field_Text != null ?
                new ObjectParameter("fld_Field_Text", fld_Field_Text) :
                new ObjectParameter("fld_Field_Text", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LookupUpdate", fld_Field_IDParameter, fld_Field_TextParameter);
        }
    }
}
