//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPanelDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_LookupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_LookupTable()
        {
            this.Tbl_LookupTable1 = new HashSet<Tbl_LookupTable>();
            this.Tbl_LookupTable11 = new HashSet<Tbl_LookupTable>();
        }
    
        public int fld_Field_ID { get; set; }
        public string fld_Field_Text { get; set; }
        public Nullable<int> fld_Field_PerantID { get; set; }
        public Nullable<int> fld_Field_DepandancyID { get; set; }
        public Nullable<bool> fld_Field_IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_LookupTable> Tbl_LookupTable1 { get; set; }
        public virtual Tbl_LookupTable Tbl_LookupTable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_LookupTable> Tbl_LookupTable11 { get; set; }
        public virtual Tbl_LookupTable Tbl_LookupTable3 { get; set; }
    }
}
