//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class asgnmt
    {
        public long asgnmt_id { get; set; }
        public Nullable<long> item_defn_id { get; set; }
        public Nullable<long> item_id { get; set; }
        public Nullable<long> field_id { get; set; }
        public Nullable<long> app_user_id { get; set; }
        public Nullable<long> team_id { get; set; }
        public string cc_email_addr { get; set; }
        public Nullable<System.DateTime> begin_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> asgnmt_type_id { get; set; }
        public bool is_team { get; set; }
        public Nullable<long> delete_txn_id { get; set; }
        public Nullable<int> sort_order { get; set; }
    
        public virtual app_user app_user { get; set; }
    }
}
